{% set name = "HYPSO-Reading" %}{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DevAlvaroF/HYPSO-Reading/archive/v0.1.0.tar.gz
  sha256: 841fc860539e3d8c6ced4cd09c3305b7c085feb8650b460e72285e55d926a0bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - numpy>=1.24.1
    - cartopy
    - pandas
    - matplotlib
    - geopandas
    - rasterio
    - gdal
    - pyproj
  run:
    - python

test:
  imports:
    - 
  commands:
    - pip check
  requires:
    - pip

about:
  license: GPL-2.0
  license_file: LICENSE
  home: https://github.com/DevAlvaroF/HYPSO-Reading
  summary: 'Visualization tool for the HYPSO satellite'
  description: |
    hypsoreader is a simple, fast, visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF
