name: Release Package
run-name: ${{ github.actor }} is releasing .tar.gz
on: [push]


jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor   # minor or  major or patch