name: Create SHA256!
run-name: ${{ github.actor }} is generatig SHA256 ${{ github.ref_name }}

#on:
#  release:
#    types: [published]

on:
  workflow_run:
    workflows: ["Release Package"]
    types:
      - completed

jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Tarball url
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ steps.previoustag.outputs.tag }}.tar.gz"
      - name: Create tarball sha256 
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ steps.previoustag.outputs.tag }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
